# Generated by Django 3.1.11 on 2021-05-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdsBottomBanner',
        ),
        migrations.DeleteModel(
            name='AdsRightBanner',
        ),
        migrations.DeleteModel(
            name='AdsTopBanner',
        ),
        migrations.AlterField(
            model_name='author',
            name='business_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
