# Generated by Django 3.1.11 on 2021-09-29 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0002_auto_20210521_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('deliver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='demand',
            name='service',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Express', 'Express')], default='Normal', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('DELIVERED', 'Delivered'), ('NOT_DELIVERED', 'Not delivered')], max_length=13)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('colis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demand', to='delivery.demand')),
                ('mandataire', models.ManyToManyField(related_name='driver', to='delivery.Driver')),
            ],
        ),
    ]
