# Generated by Django 3.1.11 on 2021-09-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20210930_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Compagny', 'Compagny')], default='Individual', max_length=10),
        ),
    ]
