# Generated by Django 3.1.11 on 2021-10-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_author_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='service',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Express', 'Express')], max_length=7),
        ),
    ]
