# Generated by Django 3.1.11 on 2022-01-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20211228_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='is_active',
            field=models.CharField(choices=[('IN PROGRESS', 'In progress'), ('PICKED', 'Picked'), ('DELIVERED', 'Delivered')], default='IN PROGRESS', max_length=11),
        ),
    ]
