# Generated by Django 3.1.7 on 2021-03-06 21:30

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('livrer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name1', models.CharField(max_length=200)),
                ('phone1', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('indication1', models.CharField(max_length=200)),
                ('address1', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
        migrations.DeleteModel(
            name='Geolocation',
        ),
    ]
