# Generated by Django 3.1.7 on 2021-03-13 04:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livrer', '0002_auto_20210306_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsBottomBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Place Your Ad', max_length=200)),
                ('image', models.ImageField(default=None, upload_to='banners/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='AdsRightBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Place Your Ad', max_length=200)),
                ('image', models.ImageField(default=None, upload_to='banners/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='AdsTopBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Place Your Ad', max_length=200)),
                ('image', models.ImageField(default=None, upload_to='banners/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='demand',
            name='indication1',
        ),
        migrations.AddField(
            model_name='demand',
            name='description1',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demand',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default-profile-pic.png', null=True, upload_to='uploads/profile-pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='demand',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livrer.author'),
        ),
    ]
