# Generated by Django 3.1.7 on 2021-03-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrer', '0003_auto_20210312_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='address1',
            new_name='autocomplete',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='description1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='phone1',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='full_name1',
            new_name='title',
        ),
    ]
