# Generated by Django 3.1.7 on 2021-03-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrer', '0004_auto_20210315_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
