# Generated by Django 3.1.7 on 2021-03-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrer', '0005_auto_20210317_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdsBottomBanner',
        ),
        migrations.DeleteModel(
            name='AdsRightBanner',
        ),
        migrations.DeleteModel(
            name='AdsTopBanner',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='author',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='autocomplete',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
    ]
