# Generated by Django 3.1.11 on 2021-05-17 10:54

import ckeditor.fields
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livrer', '0006_auto_20210318_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(choices=[('estimate', 'estimate'), ('complaints', 'complaints')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('organisation', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
