# Generated by Django 3.1.11 on 2021-06-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrer', '0008_auto_20210521_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Massages',
        ),
    ]
